kind: pipeline
name: deploy_birthdaybot

steps:
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: lp13.rpiambulance.com
      username: drone
      password:
        from_secret: SSH_PASSWORD
      port: 22
      script:
        - docker-compose -f /drone/docker-compose.yml up -d --build birthdaybot
    when:
      branch:
        - master

  - name: deploy-dev
    image: appleboy/drone-ssh
    settings:
      host: lp13.rpiambulance.com
      username: drone
      password:
        from_secret: SSH_PASSWORD
      port: 22
      script:
        - docker-compose -f /drone/docker-compose.yml up -d --build birthdaybot-dev
    when:
      branch:
        - dev
